apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: base64_encoded_root_password
  database-name: base64_encoded_database_name
  db-user: base64_encoded_db_user
  db-password: base64_encoded_db_password
